-- ============================================================================
-- 0002 — Catalog: games, ranks, services, placement/net-win price tables,
-- modifiers, regions, coupons, loyalty tiers. Seeded from the in-code catalog
-- (supabase/seed.sql, generated by `pnpm gen:seed`) so prices live in one place.
--
-- Fractional values use double precision (not numeric) so node-postgres, PGlite,
-- and PostgREST all return JS numbers — keeping price parity exact across drivers.
-- The public catalog is genuinely public (marketing data): anon may read it.
-- Coupons are NOT public (no anon grant) — validated server-side.
-- ============================================================================

create table public.games (
  slug text primary key,
  name text not null,
  short_name text not null,
  divisions_per_tier int not null,
  is_active boolean not null default true,
  sort_order int not null default 0
);

create table public.ranks (
  id uuid primary key default gen_random_uuid(),
  game_slug text not null references public.games (slug) on delete cascade,
  tier text not null,
  division int not null,
  label text not null,
  sort_index int not null,
  climb_price_cents int not null default 0 check (climb_price_cents >= 0),
  climb_eta_hours double precision not null default 0,
  is_purchasable boolean not null default true,
  unique (game_slug, sort_index)
);
create index ranks_game_sort_idx on public.ranks (game_slug, sort_index);

create table public.services (
  type service_type primary key,
  slug text not null unique,
  name text not null,
  short text not null,
  blurb text not null,
  is_active boolean not null default true,
  sort_order int not null default 0
);

create table public.placement_prices (
  id uuid primary key default gen_random_uuid(),
  game_slug text not null references public.games (slug) on delete cascade,
  band placement_band not null,
  label text not null,
  price_per_game_cents int not null check (price_per_game_cents >= 0),
  min_games int not null,
  max_games int not null,
  eta_per_game_hours double precision not null,
  unique (game_slug, band)
);

create table public.net_win_groups (
  id uuid primary key default gen_random_uuid(),
  game_slug text not null references public.games (slug) on delete cascade,
  group_key net_win_group not null,
  label text not null,
  price_per_win_cents int not null check (price_per_win_cents >= 0),
  tiers text[] not null,
  eta_per_win_hours double precision not null,
  unique (game_slug, group_key)
);

create table public.modifiers (
  key text primary key,
  label text not null,
  description text not null,
  kind modifier_kind not null,
  amount int not null,
  eta_multiplier double precision not null default 1.0,
  is_default_on boolean not null default false,
  is_active boolean not null default true,
  sort_order int not null default 0,
  game_slug text references public.games (slug) on delete cascade,
  service_type service_type,
  hidden_in_duo boolean not null default false
);

create table public.regions (
  id uuid primary key default gen_random_uuid(),
  game_slug text not null references public.games (slug) on delete cascade,
  code text not null,
  label text not null,
  multiplier double precision not null default 1.0,
  is_default boolean not null default false,
  sort_order int not null default 0,
  unique (game_slug, code)
);

create table public.coupons (
  code text primary key,
  kind coupon_kind not null,
  amount int not null,
  min_order_cents int not null default 0,
  max_uses int,
  uses int not null default 0,
  expires_at timestamptz,
  is_active boolean not null default true
);

create table public.loyalty_tiers (
  name text primary key,
  min_lifetime_spend_cents bigint not null,
  discount_bp int not null,
  cashback_bp int not null,
  sort_order int not null default 0
);

-- --- RLS: public catalog readable by anyone; admins write; service role all --
alter table public.games enable row level security;
alter table public.ranks enable row level security;
alter table public.services enable row level security;
alter table public.placement_prices enable row level security;
alter table public.net_win_groups enable row level security;
alter table public.modifiers enable row level security;
alter table public.regions enable row level security;
alter table public.loyalty_tiers enable row level security;
alter table public.coupons enable row level security;

do $$
declare t text;
begin
  foreach t in array array[
    'games','ranks','services','placement_prices','net_win_groups',
    'modifiers','regions','loyalty_tiers'
  ] loop
    execute format('grant select on public.%I to anon, authenticated', t);
    execute format('grant all on public.%I to service_role', t);
    execute format(
      'create policy %I on public.%I for select to anon, authenticated using (true)',
      t || '_select_public', t
    );
    execute format(
      'create policy %I on public.%I for all to authenticated using (public.is_admin()) with check (public.is_admin())',
      t || '_write_admin', t
    );
  end loop;
end $$;

-- Coupons: not public. Admins manage them; the service role reads/validates them
-- server-side. No grant to anon at all.
grant select, insert, update, delete on public.coupons to authenticated;
grant all on public.coupons to service_role;
create policy coupons_admin_all on public.coupons
  for all to authenticated
  using (public.is_admin()) with check (public.is_admin());
